### ISSUE TITLE
Add Selection option for multi-file operations 

### ISSUE THREAD

**Issue by khbaydoun** [WolfgangFahl/py-3rdparty-mediawiki#25]
extra Command Line option which allows a selection dialog to appear in case of multi-page operation

Multiple Checkboxes- one per page and one "all/none" option

**Comment by WolfgangFahl** [comment]
e.g. https://ux.stackexchange.com/questions/129460/group-checkboxes-select-all-none-designs-best-practices

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/100128340-734c3d80-2e80-11eb-9f30-49e03d290160.png)

**Comment by WolfgangFahl** [comment]
see https://wiki.python.org/moin/GuiProgramming for alternative libraries. Most other seem to be non standard ...

**Comment by WolfgangFahl** [comment]
The test code currently has the warning:
Fontconfig warning: ignoring UTF-8: not a valid region tag
