### ISSUE TITLE
Moving .wiki files from a local machine to a live wiki

### ISSUE THREAD

**Issue by cuppajoeman** [WolfgangFahl/py-3rdparty-mediawiki#44]
Say one has an `x.wiki` file and would like to upload that to their wiki 

There is a method to upload files from a target wiki to a destination one, but I don't need a source wiki in my case as the file is on my own physical machine.

**Comment by WolfgangFahl** [comment]
@cuppajoeman thanks for the suggestion - this is a much needed feature to complete the toolkit and a prerequisite for #21

**Comment by tholzheim** [comment]
To upload an `x.wiki` file you can now use **wikirestore**.

For example the file is located in **/home/user/documents** you can use:
   `wikirestore -t wikiId -p "x" --backupPath "/home/user/documents"`

To upload all files located at **/home/user/documents** use:
   `wikirestore -t wikiId  --backupPath "/home/user/documents"`

**Comment by cuppajoeman** [comment]
@tholzheim This is great! It means that I can turn my editing workflow into this: 
![image](https://user-images.githubusercontent.com/19198104/110193817-3ccd7980-7e04-11eb-8b0d-8e13b847a779.png)

This means my editing can all be done in my own personal environment and not through the gui interface. This will really speed up how I use my wiki. Thanks to anyone who worked on this feature!!!

Ps: here is the result of that image: http://keepaskingwhy.com/mediawiki/index.php/Field
