### ISSUE TITLE
regression: wikibackup fails with TypeError

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/py-3rdparty-mediawiki#50]
wikibackup -s wiki -q "[[modification date::>2021]]"
Start: 2021-01-02 09:15:18, End: 2021-02-09 03:47:47
wikibackup: TypeError("unsupported operand type(s) for /: 'datetime.timedelta' and 'NoneType'")
            for help use --help

**Comment by tholzheim** [comment]
Does this error still occurs after the fix of #49. I tried this before the fix and it exactly faild at "if args.queryDivision < 1:"  and was fixed with #49 see https://github.com/WolfgangFahl/py-3rdparty-mediawiki/commit/7ec8c54 . After the fix I was not able to recreate this bug.

**Comment by WolfgangFahl** [comment]
You are right
```
wikibackup -V
wikibackup v0.1.15 (2020-12-05)
```

**Comment by tholzheim** [comment]
You are right. I added a default value to the command line argument -qd. This should fix this issue.
