### ISSUE TITLE
Regression? wikipush: TypeError("argument of type 'NoneType' is not iterable")

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/py-3rdparty-mediawiki#54]
wikipush -s or -t ormk -q "[[isA::Event series]]"
wikipush: TypeError("argument of type 'NoneType' is not iterable")

**Comment by tholzheim** [comment]
I traced down the issue and the Type error comes from an incorrect handling of empty query results. I fixed this issue but found another one #55
