### ISSUE TITLE
fixAsk  alters the query semantic

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/py-3rdparty-mediawiki#82]
https://github.com/WolfgangFahl/py-3rdparty-mediawiki/blob/da18038b3d5679407726de31fe9ad1943be19840/wikibot/smw.py#L248

## Input 
```mediawiki
{{#ask:[[IsA::Event series]]
|mainlabel=pageTitle
|?EventSeries_acronym=acronym
}}
```

## Output
```mediawiki
[[IsA::Event_series]]
|mainlabel=pageTitle
|?EventSeries_acronym=acronym
```

## Expected Output
```mediawiki
[[IsA::Event series]]
|mainlabel=pageTitle
|?EventSeries_acronym=acronym
```

## Bug

We query for the string `Event series` which is escaped to `Event_series` which is only allowed for values of type [Page](https://www.semantic-mediawiki.org/wiki/Help:Type_Page). Since `fixAsk()`main purpose is to remove the `{{#ask: ...}}` circumfix and to remove the white space the replacement of blanks with an underscore should be removed or replaced by escaping a blank with `%20`

https://github.com/WolfgangFahl/py-3rdparty-mediawiki/blob/da18038b3d5679407726de31fe9ad1943be19840/wikibot/smw.py#L273

**Comment by WolfgangFahl** [comment]
What is an example for when this behavior is incorrect. Please specify situation, action and expected result.

**Comment by tholzheim** [comment]
I updated the issue description. The problem is that if the value of the selector has datatype Page the escaping with the underscore is correct. If the property has datatype string escaping the blank with the underscore alters the selector string and thus the query result

**Comment by WolfgangFahl** [comment]
identfiers with blanks are evil :-)
