### ISSUE TITLE
wikiedit allow to modify single parameter of a macro WikiSon

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/py-3rdparty-mediawiki#91]
input:
- wikiId
- pagetitle
- template/entity/WikiSon
- property/templateParam
- new value

Example:
Change googlescholar user of https://ceur-ws.bitplan.com/index.php/Tim_Berners-Lee

wikiId: ceur-ws
pagetitle: Tim_Berners-Lee
template: Scholar
param: googleScholarUser see https://ceur-ws.bitplan.com/index.php/Property:Scholar_googleScholarUser
new value: test

**Comment by WolfgangFahl** [comment]
start with API and design command line accordingly

**Comment by tholzheim** [comment]
usage example 
```bash
$ wikiedit -t "testWiki" --pages "Test" --template "WikiSON" --property "age" --value "Hello World"
editing 1 pages in researchWiki (dry run)
1/1 (100.00%): editing Test ...👍 
 {{WikiSON
 |name=Hello Wikiedit used
+|age=Hello World
 }}

```
